config/routes.rb
Rails.application.routes.draw do
  resources :interviews
  resources :refuzuars
  resources :kontrata

  get 'kontrata/new/:kontrata_id', to: 'kontrata#new', as: 'new_kontrata'
  get 'all_checked/index'

  resources :pcs
  resources :gjuhas
  resources :qytetets
  resources :dergoemails
  get 'apliko/hapi_3'
  get 'apliko/pune'
  root 'pozita#zgjidh'
  get 'pushimet/index'
  get("pozita/zgjidh")
  get("pozita/kalo")
  get("pozis/index")
  get("formularis/index")
  get("punetoris/index")
  get("statuses/index")
  get("kontrata/kontrata_print")
  resources :statuses
  resources :pozis
  resources :punetoris
  resources :punetoris do
    collection { post :search, to: 'punetoris#index' }
  end
  get 'dashboard/new'
  get 'home/index'

  resources :formularis do
    collection { post :search, to: 'formularis#index' }
  end
  devise_for :users
  get 'dergoemails/new/:id' => 'dergoemails#new', as: "new_dergoemails"
  post 'apliko/pune'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  	before_action :authenticate_user!
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
    ab(params[:lan])
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to statuses_path, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to statuses_path, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:description)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
  #_form
  def paneli(lan = "en")
    if(lan == "en")
      "Dashboard"
    else
      if(lan == "al")
        "Paneli"
      end
    end
  end
  def appi(lan = "en")
    if(lan == "en")
      "Applications"
    else
      if(lan == "al")
        "Aplikimet"
      end
    end
  end
  def puntori(lan = "en")
    if(lan == "en")
      "Workers"
    else
      if(lan == "al")
        "Punetoret"
      end
    end
  end
  def pushimet(lan = "en")
    if(lan == "en")
      "Holidays"
    else
      if(lan == "al")
        "Pushimet"
      end
    end
  end

  def status(lan = "en")
    if(lan == "en")
      "Statuses"
    else
      if(lan == "al")
        "Statuset"
      end
    end
  end
  def dil(lan = "en")
    if(lan == "en")
      "Logout"
    else
      if(lan == "al")
        "Shkyçu"
      end
    end
  end
  def refuzuar(lan = "en")
    if(lan == "en")
      "Rejected"
    else
      if(lan == "al")
        "Refuzuar"
      end
    end
  end
  def intervs(lan = "en")
    if(lan == "en")
      "Intervews"
    else
      if(lan == "al")
        "Intervista"
      end
    end
  end
  #editi
  def editi(lan = "en")
    if(lan == "en")
      "Editing Status"
    else
      if(lan == "al")
        "Ndrysho Statusit"
      end
    end
  end
  def ndrysho(lan = "en")
    if(lan == "en")
      "Edit"
    else
      if(lan == "al")
        "Ndrysho"
      end
    end
    end
    #index
    def add(lan = "en")
      if(lan == "en")
        "Add new"
      else
        if(lan == "al")
          "Regjistro Statusin"
        end
      end
    end
    def des(lan = "en")
      if(lan == "en")
        "Description"
      else
        if(lan == "al")
          "Pershkrimi"
        end
      end
    end
    def aksionet(lan = "en")
      if(lan == "en")
        "Actions"
      else
        if(lan == "al")
          "Aksionet"
        end
      end
    end
    def ndrysho(lan = "en")
      if(lan == "en")
        "EDIT"
      else
        if(lan == "al")
          "NDRYSHO"
        end
      end
    end
    def fshije(lan = "en")
      if(lan == "en")
        "DELETE"
      else
        if(lan == "al")
          "FSHIJ"
        end
      end
    end
    def kth(lan = "en")
      if(lan == "en")
        "Back"
      else
        if(lan == "al")
          "Kthehu"
        end
      end
    end
    #new
    def regj_statusi(lan = "en")
      if(lan == "en")
        "Recording Status"
      else
        if(lan == "al")
          "Regjistrimi Statusit"
        end
      end
    end
    def ruj(lan = "en")
      if(lan == "en")
        "Save"
      else
        if(lan == "al")
          "Ruaj"
        end
      end
    end
    #show
    def list_statusi(lan = "en")
      if(lan == "en")
        "Listing of positions"
      else
        if(lan == "al")
          "Listimi i pozitave"
        end
      end
    end

    def savei(lan = "en")
      if(lan == "en")
        "Save"
      else
        if(lan == "al")
          "Ruaj"
        end
      end
    end

    def closi(lan = "en")
      if(lan == "en")
        "Close"
      else
        if(lan == "al")
          "Mbyll"
        end
      end
    end

    def newi2(lan = "en")
      if(lan == "en")
        "New Status"
      else
        if(lan == "al")
          "Status i ri"
        end
      end
    end
end

app/views/statuses/_form.html.erb
<div id="wrapper">
 <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a href="#">
          HRM Project
        </a>
      </li>
      <li>
        <%= link_to "#{paneli(session[:lan])}", dashboard_new_path%>
      </li>
      <li>
        <%= link_to "#{appi(session[:lan])}", formularis_path %>
      </li>
      <li>
        <%= link_to "#{regj_statusi(session[:lan])}", new_punetori_path %>
      </li>
      <li>
      <%= link_to "#{pozita(session[:lan])}", pozis_path %>
    </li>
    <li>
      <%= link_to "#{statusi(session[:lan])}", statuses_path %>
    </li>
      <li>
        <%= link_to "#{puntori(session[:lan])}" %>
      </li>
      <li>
        <%= link_to "Pushimet" %>
      </li>
      <li>
        <%= link_to "#{qytet(session[:lan])}", qytetets_path %>
      </li>
      <li>
        <%= link_to "#{gjuha(session[:lan])}", qytetets_path %>
      </li>
      <li>
        <%= link_to "#{pc(session[:lan])}", pcs_path %>
      </li>
         <li>
                        <%= link_to "#{refuzuar(session[:lan])}", refuzuars_path%>
                    </li>
                    <li >
                        <%= link_to "#{intervs(session[:lan])}", interviews_path%>
                    </li>
      <li>
        <%= link_to "Profili im" %>
      </li>
      <li>
        <%= link_to "#{dil(session[:lan])}", destroy_user_session_path, :method => 'delete' %>
      </li>
    </ul>
  </div>
  <!-- /#sidebar-wrapper -->

<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/statuses/edit.html.erb
<% if current_user.admin? %>
<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">UBT</a>
            </div>
            <!-- Top Menu Items -->
          <ul class="nav navbar-right top-nav">
      <li><%= link_to("En", "/statuses/index/?lan=en") %></li>
      <li><%= link_to("Al", "/statuses/index/?lan=al") %></li>
       <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-bell"></i>
          <b class = "numri">
          <%if Formulari.where(status_id: 1).count>0%>
              <%=Formulari.where(status_id: 1).count%>
          <%end%>
          </b>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu alert-dropdown">
        <%Formulari.where(status_id: 1).each do |f|%>
          <li>
            <a href="formularis/<%=f.id%>"><%= f.emri%> <%= f.mbiemri%>
              <span class="label label-default"><%= f.pozita%></span>
            </a>
          </li>
            <%end%>
          <li class="divider"></li>
          <li>
            <%= link_to "View All", formularis_path %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to "#{dil(session[:lan])}", destroy_user_session_path, :method => 'delete', class: "fa fa-sign-out", style: "margin-right:20px;" %>
      </li>
    </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "#{pan(session[:lan])}", dashboard_new_path, class: "fa fa-dashboard" %>
                    </li>
                    <li >
                        <%= link_to "#{apli(session[:lan])}", formularis_path, class: "fa fa-list" %>
                    </li>
                    <li>
                        <%= link_to "#{puntori(session[:lan])}", punetoris_path, class: "fa fa-users" %>
                    </li>
                    <li>
                        <%= link_to "#{push(session[:lan])}" , pushimet_index_path, class: "fa fa-calendar" %>
                    </li>
                    <li >
                        <%= link_to "#{pozit(session[:lan])}", pozis_path, class: "fa fa-bars"  %>
                    </li>
                    <li    class="active">
                        <%= link_to "#{status(session[:lan])}", statuses_path, class: "fa fa-check-square-o" %>
                    </li>
                    <li>
                        <%= link_to "#{qytet(session[:lan])}", qytetets_path, class: "fa fa-building" %>
                    </li>
                    <li >
                        <%= link_to "#{gjuha(session[:lan])}",gjuhas_path, class: "fa fa-language" %>
                    </li>
                    <li>
                        <%= link_to "#{pc(session[:lan])}", pcs_path, class: "fa fa-laptop" %>
                    </li>
                       <li>
                        <%= link_to "#{refuzuar(session[:lan])}", refuzuars_path, class: "fa fa-adjust"%>
                    </li>
                    <li >
                        <%= link_to "#{intervs(session[:lan])}", interviews_path, class: "fa fa-male" %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h2 class="page-header">
                            <%= editi(session[:lan]) %>
                        </h2>
                         <% if notice %>
                          <p class="notice"><%= notice %></p>
                          <% elsif alert %>
                          <p class="alert"><%= alert %></p>
                          <% end %>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-check-square-o" style="color:#777;"></i>  <a style="color:#777;" href="index.html">Statusi</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-edit"></i> <%= ndrysho(session[:lan]) %>
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->



                <div class="row">
                    <div class="col-lg-12">
                        <div class="b_g">

                            <div class="border_punetori" style="height: 155px;">

                                <%= form_for(@status) do |f| %>
                                      <% if @status.errors.any? %>
                                        <div id="error_explanation">
                                          <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

                                          <ul>
                                          <% @status.errors.full_messages.each do |message| %>
                                            <li><%= message %></li>
                                          <% end %>
                                          </ul>
                                        </div>
                                      <% end %>

                                      <div class="field">
                                        <div class="col-md-4"><%= f.label :description %></div>
                                        <div class="col-md-8"><%= f.text_field :description,  class: "punetori_input" %></div>
                                      </div>

                                    <%= link_to  "#{kth(session[:lan])}", statuses_path, :class => "back_btn", style: "margin-top: 35px;" %>

                                  <div class="col-md-8"><div class="actions formulari_btn">
                                    <%= f.submit "#{ndrysho(session[:lan])}" , style: "margin-right:120px;" %></div>
                                  </div>
                                  <% end %>






                    </div>
            <!-- /.container-fluid -->
                </div>
        </div>
        <!-- /#page-wrapper -->

    </div>
  <% end %>

app/views/statuses/index.html.erb
<% if current_user.admin? %>
<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">UBT</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
              <li><%= link_to("En", "/statuses/index/?lan=en") %></li>
              <li><%= link_to("Al", "/statuses/index/?lan=al") %></li>
                 <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <i class="fa fa-bell"></i>
                      <b class = "numri">
                      <%if Formulari.where(status_id: 1).count>0%>
                          <%=Formulari.where(status_id: 1).count%>
                      <%end%>
                      </b>
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu alert-dropdown">
                    <%Formulari.where(status_id: 1).each do |f|%>
                      <li>
                        <a href="formularis/<%=f.id%>"><%= f.emri%> <%= f.mbiemri%>
                          <span class="label label-default"><%= f.pozita%></span>
                        </a>
                      </li>
                        <%end%>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "View All", formularis_path %>
                      </li>
                    </ul>
                </li>
                 <li>
                     <%= link_to "#{dil(session[:lan])}", destroy_user_session_path, :method => 'delete', class: "fa fa-sign-out", style: "margin-right:20px;" %>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
             <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "#{paneli(session[:lan])}", dashboard_new_path, class: "fa fa-dashboard" %>
                    </li>
                    <li >
                        <%= link_to "#{appi(session[:lan])}", formularis_path, class: "fa fa-list" %>
                    </li>

                    <li>
                        <%= link_to "#{puntori(session[:lan])}", punetoris_path, class: "fa fa-users" %>
                    </li>
                    <li>
                        <%= link_to "#{pushimet(session[:lan])}" , pushimet_index_path, class: "fa fa-calendar" %>
                    </li>
                    <li>
                        <%= link_to "#{pozita(session[:lan])}", pozis_path, class: "fa fa-bars"  %>
                    </li>
                    <li     class="active">
                        <%= link_to "#{statusi(session[:lan])}", statuses_path, class: "fa fa-check-square-o" %>
                    </li>
                    <li>
                        <%= link_to "#{qytet(session[:lan])}", qytetets_path, class: "fa fa-building" %>
                    </li>
                    <li >
                        <%= link_to "#{gjuha(session[:lan])}",gjuhas_path, class: "fa fa-language" %>
                    </li>
                    <li>
                        <%= link_to "#{pc(session[:lan])}", pcs_path, class: "fa fa-laptop" %>
                    </li>
                       <li>
                        <%= link_to "#{refuzuar(session[:lan])}", refuzuars_path, class: "fa fa-adjust"%>
                    </li>
                    <li >
                        <%= link_to "#{intervs(session[:lan])}", interviews_path, class: "fa fa-male" %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h2 class="page-header">
                            <%= statusi(session[:lan]) %>
                        </h2>
                         <% if notice %>
                          <p class="notice"><%= notice %></p>
                          <% elsif alert %>
                          <p class="alert"><%= alert %></p>
                          <% end %>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard" style="color:#777;"></i>  <a style="color:#777;" href="index.html"><%= paneli(session[:lan]) %></a>
                            </li>
                            <li class="active">
                                <i class="fa fa-check-square-o"></i><%= statusi(session[:lan]) %>
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->



                <div class="row">
                    <div class="col-lg-12">


                        <div class="b_g">

                            <div class="exeli">
                              <%= link_to "Excel", formularis_path(format: "xls"), class: "butoni_e pull-right fa fa-upload ", style: "color: #777;"%>
                            </div>
                            <%= link_to "#{add(session[:lan])}","#",class: "fa fa-plus regj_p" , "data-toggle" => "modal", "data-target" => "#exampleModal" %>
                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                              <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="exampleModalLabel"><%= "#{newi2(session[:lan])}" %></h4>
                                  </div>
                                  <div class="modal-body">

                                          <%= form_for Status.new do |f| %>
                                           <div class="form-group">
                                                <%= f.label :description, class: "control-label" %><br>
                                                <%= f.text_field :description, class: "form-control" %>
                                              </div>

                                              <%= f.submit "#{savei(session[:lan])}", class: "btn btn-primary" %>
                                          <% end %>
                                                  <button type="button" style="margin:0px;float:right;margin-top:-80px;"class="btn btn-default" data-dismiss="modal"><%=  "#{closi(session[:lan])}"%></button>
                                  </div>

                                </div>
                              </div>
                            </div>

                            <table class="table">
                                <thead>
                                  <th><%= des(session[:lan]) %></th>
                                  <th><%= aksionet(session[:lan]) %></th>
                                </thead>
                                <% @statuses.each do |status| %>
                                <tr>
                                  <td><%= status.description %></td>
                                <% if can? :update, status %>
                                <td><%= link_to "#{ndrysho(session[:lan])}", edit_status_path(status), class: "edit" %>
                                <% end %>

                                <% if can? :update, status %>
                                <%= link_to "#{fshije(session[:lan])}", status, method: :delete, data: { confirm: 'A jeni te sigurt?' }, class: "fshij" %>
                                  <% end %>
                                </td>
                                      <% end %>

                            </table>
                            <%= link_to "#{kth(session[:lan])}", dashboard_new_path, :class => "back_btn", style: "margin-top: 35px;" %>
                        </div>
                        <% end %>
                    </div>
            <!-- /.container-fluid -->
                </div>
        </div>
        <!-- /#page-wrapper -->

    </div>

app/views/statuses/new.html.erb
<% if current_user.admin? %>
<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">UBT</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
      <li><%= link_to("En", "/statuses/index/?lan=en") %></li>
      <li><%= link_to("Al", "/statuses/index/?lan=al") %></li>
       <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-bell"></i>
          <b class = "numri">
          <%if Formulari.where(status_id: 1).count>0%>
              <%=Formulari.where(status_id: 1).count%>
          <%end%>
          </b>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu alert-dropdown">
        <%Formulari.where(status_id: 1).each do |f|%>
          <li>
            <a href="formularis/<%=f.id%>"><%= f.emri%> <%= f.mbiemri%>
              <span class="label label-default"><%= f.pozita%></span>
            </a>
          </li>
            <%end%>
          <li class="divider"></li>
          <li>
            <%= link_to "View All", formularis_path %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to "#{dil(session[:lan])}", destroy_user_session_path, :method => 'delete', class: "fa fa-sign-out", style: "margin-right:20px;" %>
      </li>
    </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
             <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "#{paneli(session[:lan])}", dashboard_new_path, class: "fa fa-dashboard" %>
                    </li>
                    <li >
                        <%= link_to "#{appi(session[:lan])}", formularis_path, class: "fa fa-list" %>
                    </li>
                    <li>
                        <%= link_to "#{puntori(session[:lan])}", punetoris_path, class: "fa fa-users" %>
                    </li>
                    <li>
                        <%= link_to "#{pushimet(session[:lan])}" , pushimet_index_path, class: "fa fa-calendar" %>
                    </li>
                    <li>
                        <%= link_to "#{pozita(session[:lan])}", pozis_path, class: "fa fa-bars"  %>
                    </li>
                    <li   class="active" >
                        <%= link_to "#{statusi(session[:lan])}", statuses_path, class: "fa fa-check-square-o" %>
                    </li>
                    <li>
                        <%= link_to "#{qytet(session[:lan])}", qytetets_path, class: "fa fa-building" %>
                    </li>
                    <li >
                        <%= link_to "#{gjuha(session[:lan])}",gjuhas_path, class: "fa fa-language" %>
                    </li>
                    <li>
                        <%= link_to "#{pc(session[:lan])}", pcs_path, class: "fa fa-laptop" %>
                    </li>
                       <li>
                        <%= link_to "#{refuzuar(session[:lan])}", refuzuars_path, class: "fa fa-adjust"%>
                    </li>
                    <li >
                        <%= link_to "#{intervs(session[:lan])}", interviews_path, class: "fa fa-male"%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h2 class="page-header">
                            <%= add(session[:lan]) %>
                        </h2>
                         <% if notice %>
                          <p class="notice"><%= notice %></p>
                          <% elsif alert %>
                          <p class="alert"><%= alert %></p>
                          <% end %>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-check-square-o" style="color:#777;"></i>  <a style="color:#777;" href="index.html"><%= statusi(session[:lan]) %></a>
                            </li>
                            <li class="active">
                                <i class="fa fa-history"></i> <%= add(session[:lan]) %>
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->



                <div class="row">
                    <div class="col-lg-12">
                        <div class="b_g">
                            <%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

                                <div class="field">
                                  <div class="col-sm-4">
                                    <%= f.label :description %></div>
                                  <div class="col-sm-8">
                                    <%= f.text_field :description, class: "punetori_input" %></div>
                                </div>
                              <div class="actions">
                                <div class="actions formulari_btn" style="margin-right:438px"><%= f.submit "#{ruj(session[:lan])}" %></div>
                              </div>
                            <% end %>
                        </div>
                    </div>
            <!-- /.container-fluid -->
                </div>
        </div>
        <!-- /#page-wrapper -->

    </div>

<% end %>