config/routes.rb
Rails.application.routes.draw do
  resources :interviews
  resources :refuzuars
  resources :kontrata

  get 'kontrata/new/:kontrata_id', to: 'kontrata#new', as: 'new_kontrata'
  get 'all_checked/index'

  resources :pcs
  resources :gjuhas
  resources :qytetets
  resources :dergoemails
  get 'apliko/hapi_3'
  get 'apliko/pune'
  root 'pozita#zgjidh'
  get 'pushimet/index'
  get("pozita/zgjidh")
  get("pozita/kalo")
  get("pozis/index")
  get("formularis/index")
  get("punetoris/index")
  get("statuses/index")
  get("kontrata/kontrata_print")
  resources :statuses
  resources :pozis
  resources :punetoris
  resources :punetoris do
    collection { post :search, to: 'punetoris#index' }
  end
  get 'dashboard/new'
  get 'home/index'

  resources :formularis do
    collection { post :search, to: 'formularis#index' }
  end
  devise_for :users
  get 'dergoemails/new/:id' => 'dergoemails#new', as: "new_dergoemails"
  post 'apliko/pune'

end

app/models/pc.rb
class Pc < ActiveRecord::Base
end

app/controllers/pcs_controller.rb
class PcsController < ApplicationController
  before_action :set_pc, only: [:show, :edit, :update, :destroy]

  # GET /pcs
  # GET /pcs.json
  def index
    @pcs = Pc.all
  end

  # GET /pcs/1
  # GET /pcs/1.json
  def show
  end

  # GET /pcs/new
  def new
    @pc = Pc.new
  end

  # GET /pcs/1/edit
  def edit
  end

  # POST /pcs
  # POST /pcs.json
  def create
    @pc = Pc.new(pc_params)

    respond_to do |format|
      if @pc.save
        format.html { redirect_to @pc, notice: 'Pc was successfully created.' }
        format.json { render :show, status: :created, location: @pc }
      else
        format.html { render :new }
        format.json { render json: @pc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pcs/1
  # PATCH/PUT /pcs/1.json
  def update
    respond_to do |format|
      if @pc.update(pc_params)
        format.html { redirect_to @pc, notice: 'Pc was successfully updated.' }
        format.json { render :show, status: :ok, location: @pc }
      else
        format.html { render :edit }
        format.json { render json: @pc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pcs/1
  # DELETE /pcs/1.json
  def destroy
    @pc.destroy
    respond_to do |format|
      format.html { redirect_to pcs_url, notice: 'Pc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pc
      @pc = Pc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pc_params
      params.require(:pc).permit(:description)
    end
end

app/helpers/pcs_helper.rb
module PcsHelper
  #_form
  def paneli(lan = "en")
    if(lan == "en")
      "Dashboard"
    else
      if(lan == "al")
        "Paneli"
      end
    end
  end
  def appi(lan = "en")
    if(lan == "en")
      "Applications"
    else
      if(lan == "al")
        "Aplikimet"
      end
    end
  end
  def puntori(lan = "en")
    if(lan == "en")
      "Workers"
    else
      if(lan == "al")
        "Punetoret"
      end
    end
  end
  def pushimet(lan = "en")
    if(lan == "en")
      "Holidays"
    else
      if(lan == "al")
        "Pushimet"
      end
    end
  end

  def status(lan = "en")
    if(lan == "en")
      "Statuses"
    else
      if(lan == "al")
        "Statuset"
      end
    end
  end
  def dil(lan = "en")
    if(lan == "en")
      "Log Out"
    else
      if(lan == "al")
        "Shkyçu"
      end
    end
  end
  def refuzuar(lan = "en")
    if(lan == "en")
      "Rejected"
    else
      if(lan == "al")
        "Refuzuar"
      end
    end
  end
  def intervs(lan = "en")
    if(lan == "en")
      "Intervews"
    else
      if(lan == "al")
        "Intervista"
      end
    end
  end
  #edit
  def edit_pc(lan = "en")
    if(lan == "en")
      "Editing Pc"
    else
      if(lan == "al")
        " Editimi Kompjuter"
      end
    end
    end
    def edit_q(lan = "en")
      if(lan == "en")
        "Edit"
      else
        if(lan == "al")
          "Ndrysho"
        end
      end
      end

    #index

    def des(lan = "en")
      if(lan == "en")
        "Description"
      else
        if(lan == "al")
          "Pershkrimi"
        end
      end
    end
    def ndrysho(lan = "en")
      if(lan == "en")
        "EDIT"
      else
        if(lan == "al")
          "NDRYSHO"
        end
      end
    end
    def fshije(lan = "en")
      if(lan == "en")
        "DELETE"
      else
        if(lan == "al")
          "FSHIJ"
        end
      end
    end
    def kth(lan = "en")
      if(lan == "en")
        "Back"
      else
        if(lan == "al")
          "Kthehu"
        end
      end
    end
    #new
    def ruj(lan = "en")
      if(lan == "en")
        "Save"
      else
        if(lan == "al")
          "Ruaj"
        end
      end
    end
    def regj_pc(lan = "en")
      if(lan == "en")
        "Add new"
      else
        if(lan == "al")
          "Regjistro Kompjuter"
        end
      end
    end
    def rgj_pc(lan = "en")
      if(lan == "en")
        "Recording Pc"
      else
        if(lan == "al")
          "Regjistrimi Pc"
        end
      end
    end
    def list_pc(lan = "en")
      if(lan == "en")
        "Listing of Pc"
      else
        if(lan == "al")
          "Listimi i Pc"
        end
      end
    end
    def savei(lan = "en")
      if(lan == "en")
        "Save"
      else
        if(lan == "al")
          "Ruaj"
        end
      end
    end

    def closi(lan = "en")
      if(lan == "en")
        "Close"
      else
        if(lan == "al")
          "Mbyll"
        end
      end
    end
    def newi(lan = "en")
      if(lan == "en")
        "New City"
      else
        if(lan == "al")
          "Qyteti i ri"
        end
      end
    end
    def gjuha(lan = "en")
      if(lan == "en")
        "Language"
      else
        if(lan == "al")
          "Gjuha"
        end
      end
    end
    def pc(lan = "en")
      if(lan == "en")
        "PC"
      else
        if(lan == "al")
          "Kompjuter"
        end
      end
    end
end

app/views/pcs/_form.html.erb
<div id="wrapper">
 <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a href="#">
          HRM Project
        </a>
      </li>
      <li>
        <%= link_to "#{paneli(session[:lan])}", dashboard_new_path%>
      </li>
      <li>
        <%= link_to "#{appi(session[:lan])}", formularis_path %>
      </li>
      <li>
        <%= link_to "#{rgj_pozita(session[:lan])}", new_punetori_path %>
      </li>
      <li>
      <%= link_to "#{pozita(session[:lan])}", pozis_path %>
    </li>
    <li>
      <%= link_to "#{statusi(session[:lan])}", statuses_path %>
    </li>
      <li>
        <%= link_to "#{puntori(session[:lan])}" %>
      </li>
      <li>
        <%= link_to "Pushimet" %>
      </li>
      <li>
        <%= link_to "#{qytet(session[:lan])}", qytetets_path %>
      </li>
      <li>
        <%= link_to "#{gjuha(session[:lan])}", gjuhas_path %>
      </li>
      <li>
        <%= link_to "#{pc(session[:lan])}", pcs_path %>
      </li>
      <li>
        <%= link_to "Profili im" %>
      </li>
      <li>
        <%= link_to "Dil", destroy_user_session_path, :method => 'delete' %>
      </li>
    </ul>
  </div>
  <!-- /#sidebar-wrapper -->

  <!--/Page Pozita -->
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <h2><%= edit_pc(session[:lan]) %></h2><br>
      <div class="row">
        <div class="col-lg-12 border_punetor">
        <%= form_for(@pc) do |f| %>
          <% if @pcs.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@pc.errors.count, "error") %> prohibited this gjuha from being saved:</h2>

              <ul>
              <% @pc.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :description %><br>
            <%= f.text_field :description %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
        <!-- /end Page Pozita -->
      </div>
      <!-- /#wrapper -->

app/views/pcs/edit.html.erb
<% if current_user.admin? %>
<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">UBT</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                 <li>
                     <%= link_to "#{shk(session[:lan])}", destroy_user_session_path, :method => 'delete', class: "fa fa-sign-out", style: "margin-right:20px;" %>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "#{pan(session[:lan])}", dashboard_new_path, class: "fa fa-dashboard" %>
                    </li>
                    <li >
                        <%= link_to "#{apli(session[:lan])}", formularis_path, class: "fa fa-list" %>
                    </li>
                    <li>
                        <%= link_to "#{pun(session[:lan])}", punetoris_path, class: "fa fa-users" %>
                    </li>
                    <li>
                        <%= link_to "#{push(session[:lan])}" , pushimet_index_path, class: "fa fa-calendar" %>
                    </li>
                    <li >
                        <%= link_to "#{pozit(session[:lan])}", pozis_path, class: "fa fa-bars"  %>
                    </li>
                    <li    >
                        <%= link_to "#{status(session[:lan])}", statuses_path, class: "fa fa-check-square-o" %>
                    </li>
                    <li >
                        <%= link_to "#{qytet(session[:lan])}", qytetets_path, class: "fa fa-building" %>
                    </li>
                    <li >
                        <%= link_to "#{gjuha(session[:lan])}",gjuhas_path, class: "fa fa-language" %>
                    </li>
                    <li class="active">
                        <%= link_to "#{pc(session[:lan])}", pcs_path, class: "fa fa-laptop" %>
                    </li>
                    <li >
                        <%= link_to "#{refuzuar(session[:lan])}", refuzuars_path, class: "fa fa-adjust"  %>
                    </li>
                    <li >
                        <%= link_to "#{intervs(session[:lan])}", interviews_path, class: "fa fa-male"  %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h2 class="page-header">
                          <%= edit_pc(session[:lan]) %>
                      </h2>
                       <% if notice %>
                        <p class="notice"><%= notice %></p>
                        <% elsif alert %>
                        <p class="alert"><%= alert %></p>
                        <% end %>
                      <ol class="breadcrumb">
                          <li>
                              <i class="fa fa-check-square-o" style="color:#777;"></i>  <a style="color:#777;" href="index.html"><%= pc(session[:lan]) %></a>
                          </li>
                          <li class="active">
                              <i class="fa fa-edit"></i> <%= edit_pc(session[:lan]) %>
                          </li>
                      </ol>
                  </div>
              </div>
              <!-- /.row -->



              <div class="row">
                  <div class="col-lg-12">
                      <div class="b_g">

                          <div class="border_punetori" style="height: 155px;">

                              <%= form_for(@pc) do |f| %>
                                    <% if @pc.errors.any? %>
                                      <div id="error_explanation">
                                        <h2><%= pluralize(@pc.errors.count, "error") %> prohibited this status from being saved:</h2>

                                        <ul>
                                        <% @pc.errors.full_messages.each do |message| %>
                                          <li><%= message %></li>
                                        <% end %>
                                        </ul>
                                      </div>
                                    <% end %>

                                    <div class="field">
                                      <div class="col-md-4"><%= f.label :description %></div>
                                      <div class="col-md-8"><%= f.text_field :description,  class: "punetori_input" %></div>
                                    </div>

                                  <%= link_to  "#{kth(session[:lan])}", pcs_path, :class => "back_btn", style: "margin-top: 35px;" %>

                                <div class="col-md-8"><div class="actions formulari_btn">
                                  <%= f.submit "#{ndrysho(session[:lan])}" , style: "margin-right:120px;" %></div>
                                </div>
                                <% end %>
                  </div>
          <!-- /.container-fluid -->
              </div>
      </div>
      <!-- /#page-wrapper -->

  </div>
<% end %>

app/views/pcs/index.html.erb
<% if current_user.admin? %>
<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">UBT</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
              <li><%= link_to("En", "/pozis/index/?lan=en") %></li>
              <li><%= link_to("Al", "/pozis/index/?lan=al") %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-bell"></i>
                    <b class = "numri">
                    <%if Formulari.where(status_id: 1).count>0%>
                        <%=Formulari.where(status_id: 1).count%>
                    <%end%>
                    </b>
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu alert-dropdown">
                  <%Formulari.where(status_id: 1).each do |f|%>
                    <li>
                      <a href="formularis/<%=f.id%>"><%= f.emri%> <%= f.mbiemri%>
                        <span class="label label-default"><%= f.pozita%></span>
                      </a>
                    </li>
                      <%end%>
                    <li class="divider"></li>
                    <li>
                      <a href="#">View All</a>
                    </li>
                  </ul>
      </li>
                 <li>
                     <%= link_to "#{dil(session[:lan])}", destroy_user_session_path, :method => 'delete', class: "fa fa-sign-out", style: "margin-right:20px;" %>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "#{paneli(session[:lan])}", dashboard_new_path, class: "fa fa-dashboard" %>
                    </li>
                    <li >
                        <%= link_to "#{appi(session[:lan])}", formularis_path, class: "fa fa-list" %>
                    </li>
                    <li>
                        <%= link_to "#{puntori(session[:lan])}", punetoris_path, class: "fa fa-users" %>
                    </li>
                    <li>
                        <%= link_to "#{pushimet(session[:lan])}", pushimet_index_path, class: "fa fa-calendar" %>
                    </li>
                    <li  >
                        <%= link_to "#{pozita(session[:lan])}", pozis_path, class: "fa fa-bars"  %>
                    </li>
                    <li>
                        <%= link_to "#{statusi(session[:lan])}", statuses_path, class: "fa fa-check-square-o" %>
                    </li>
                    <li >
                        <%= link_to "#{qytet(session[:lan])}", qytetets_path, class: "fa fa-building" %>
                    </li>
                    <li  >
                        <%= link_to "#{gjuha(session[:lan])}", gjuhas_path, class: "fa fa-language" %>
                    </li>
                    <li class="active">
                        <%= link_to "#{pc(session[:lan])}", pcs_path, class: "fa fa-laptop" %>
                    </li>
                    <li >
                        <%= link_to "#{refuzuar(session[:lan])}", refuzuars_path, class: "fa fa-adjust"  %>
                    </li>
                    <li >
                        <%= link_to "#{intervs(session[:lan])}", interviews_path, class: "fa fa-male"  %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h2 class="page-header">
                          <%= pc(session[:lan]) %>
                      </h2>
                      <% if notice %>
                       <p class="notice"><%= notice %></p>
                       <% elsif alert %>
                       <p class="alert"><%= alert %></p>
                       <% end %>
                     <ol class="breadcrumb">
                         <li>
                             <i class="fa fa-dashboard" style="color:#777;"></i>  <a style="color:#777;" href="index.html"><%= paneli(session[:lan]) %></a>
                         </li>
                         <li class="active">
                             <i class="fa fa-bars"></i><%= pc(session[:lan]) %>
                         </li>
                     </ol>
                 </div>
             </div>
             <!-- /.row -->
             <div class="row">
                 <div class="col-lg-12">
                     <div class="b_g">

                         <div class="exeli">
                           <%= link_to "Excel", formularis_path(format: "xls"), class: "butoni_e pull-right fa fa-upload ", style: "color: #777;"%>
                         </div>
                         <%= link_to "#{regj_pc(session[:lan])}","#",class: "fa fa-plus regj_p" , "data-toggle" => "modal", "data-target" => "#exampleModal" %>

                     <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                       <div class="modal-dialog" role="document">
                         <div class="modal-content">
                           <div class="modal-header">
                             <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                             <h4 class="modal-title" id="exampleModalLabel"><%= "#{newi(session[:lan])}" %></h4>
                           </div>
                           <div class="modal-body">
                             <%= form_for Pc.new do |f| %>
                              <div class="form-group">
                                   <%= f.label :description, class: "control-label" %><br>
                                   <%= f.text_field :description, class: "form-control" %>
                                 </div>
                                 <%= f.submit "#{savei(session[:lan])}", class: "btn btn-primary" %>
                             <% end %>
                                     <button type="button" style="margin:0px;float:right;margin-top:-80px;"class="btn btn-default" data-dismiss="modal"><%=  "#{closi(session[:lan])}"%></button>
                     </div>

                   </div>
                 </div>
               </div>
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Description</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @pcs.each do |pc| %>
                        <tr>
                          <td><%= pc.description %></td>
                          <% if can? :update, pc %>
                          <td><%= link_to "#{ndrysho(session[:lan])}", edit_pc_path(pc), class: "edit" %>
                            <% end %>
                            <% if can? :update, pc %>
                            <%= link_to "#{fshije(session[:lan])}", pc, method: :delete, data: { confirm: 'A jeni te sigurt?' }, class: "fshij" %>
                              <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <%= link_to "#{kth(session[:lan])}", dashboard_new_path, :class => "back_btn", style: "margin-top: 35px;" %>
              </div>
            </div>
            <!-- /.container-fluid -->
            </div>
            </div>
            <!-- /#page-wrapper -->

            </div>
            <% end %>

app/views/pcs/new.html.erb
<% if current_user.admin? %>
<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">UBT</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                 <li>
                     <%= link_to "#{dil(session[:lan])}", destroy_user_session_path, :method => 'delete', class: "fa fa-sign-out", style: "margin-right:20px;" %>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "#{paneli(session[:lan])}", dashboard_new_path, class: "fa fa-dashboard" %>
                    </li>
                    <li >
                        <%= link_to "#{appi(session[:lan])}", formularis_path, class: "fa fa-list" %>
                    </li>
                    <li>
                        <%= link_to "#{puntori(session[:lan])}", punetoris_path, class: "fa fa-users" %>
                    </li>
                    <li>
                        <%= link_to "#{pushimet(session[:lan])}" , pushimet_index_path, class: "fa fa-calendar" %>
                    </li>
                    <li >
                        <%= link_to "#{pozita(session[:lan])}", pozis_path, class: "fa fa-bars"  %>
                    </li>
                    <li>
                        <%= link_to "#{statusi(session[:lan])}", statuses_path, class: "fa fa-check-square-o" %>
                    </li>
                    <li >
                        <%= link_to "#{qytet(session[:lan])}", qytetets_path, class: "fa fa-building" %>
                    </li>
                    <li >
                        <%= link_to "#{gjuha(session[:lan])}", gjuhas_path, class: "fa fa-language" %>
                    </li>
                    <li class="active">
                        <%= link_to "#{pc(session[:lan])}", pcs_path, class: "fa fa-laptop" %>
                    </li>
                    <li >
                        <%= link_to "#{refuzuar(session[:lan])}", refuzuars_path, class: "fa fa-adjust"  %>
                    </li>
                    <li >
                        <%= link_to "#{intervs(session[:lan])}", interviews_path, class: "fa fa-male"  %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h2 class="page-header">
                          <h2 class="page-header">
                            <%= rgj_pc(session[:lan]) %>
                        </h2>
                         <% if notice %>
                          <p class="notice"><%= notice %></p>
                          <% elsif alert %>
                          <p class="alert"><%= alert %></p>
                          <% end %>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-bars" style="color:#777;"></i>  <a style="color:#777;" href="index.html"><%= pc(session[:lan]) %></a>
                            </li>
                            <li class="active">
                                <i class="fa fa-history"></i> <%= rgj_pc(session[:lan]) %>
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">
                    <div class="col-lg-12">
                        <div class="b_g">
                           <%= form_for(@pc) do |f| %>
                           <% if @pc.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(@pc.errors.count, "error") %> prohibited this pozi from being saved:</h2>

                              <ul>
                              <% @pc.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <% end %>
                              </ul>
                            </div>
                          <% end %>

                                 <div class="field">
                                     <div class="col-sm-4">
                                       <%= f.label :description %></div>
                                     <div class="col-sm-8">
                                       <%= f.text_field :description, class: "punetori_input" %></div>
                                   </div>
                    <div class="actions">
                      <div class="actions formulari_btn" style="margin-right:438px"><%= f.submit "#{ruj(session[:lan])}" %></div>
                    </div>
                  <% end %>


                           </div>
                       </div>
               <!-- /.container-fluid -->
                   </div>
           </div>
           <!-- /#page-wrapper -->

       </div>
     <% end %>

<%= link_to 'Back', pcs_path %>