config/routes.rb
Rails.application.routes.draw do
  resources :interviews
  resources :refuzuars
  resources :kontrata

  get 'kontrata/new/:kontrata_id', to: 'kontrata#new', as: 'new_kontrata'
  get 'all_checked/index'

  resources :pcs
  resources :gjuhas
  resources :qytetets
  resources :dergoemails
  get 'apliko/hapi_3'
  get 'apliko/pune'
  root 'pozita#zgjidh'
  get 'pushimet/index'
  get("pozita/zgjidh")
  get("pozita/kalo")
  get("pozis/index")
  get("formularis/index")
  get("punetoris/index")
  get("statuses/index")
  get("kontrata/kontrata_print")
  resources :statuses
  resources :pozis
  resources :punetoris
  resources :punetoris do
    collection { post :search, to: 'punetoris#index' }
  end
  get 'dashboard/new'
  get 'home/index'

  resources :formularis do
    collection { post :search, to: 'formularis#index' }
  end
  devise_for :users
  get 'dergoemails/new/:id' => 'dergoemails#new', as: "new_dergoemails"
  post 'apliko/pune'

end

app/models/punetori.rb
class Punetori < ActiveRecord::Base
  def self.ransackable_attributes(auth_object = nil)
		super - ['id', 'created_at', 'updated_at']
	end


   validates :emri, :mbiemri,  presence: true
   has_many :formularis
   has_one :kontratum

      before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
             format: { with: VALID_EMAIL_REGEX },
             uniqueness: { case_sensitive: false }
end

app/controllers/punetoris_controller.rb
class PunetorisController < ApplicationController
  before_action :authenticate_user!
  before_action :set_punetori, only: [:show, :edit, :update, :destroy]

  # GET /punetoris
  # GET /punetoris.json
  def index
     @formulari = Formulari.all
    ab(params[:lan])
      @search = Punetori.search(params[:q])
      @punetoris = @search.result
      @search.build_condition if @search.conditions.empty?
      @search.build_sort if @search.sorts.empty?
      respond_to do |format|
      format.html
      format.csv { send_data @formularis.to_csv }
      format.xls
      end
  end

  # GET /punetoris/1
  # GET /punetoris/1.json
  def show
    @status = Status.all
    @pozi = Pozi.all
    @qytetets= Qytetet.all
    @gjuhas=Gjuha.all
    @pcs=Pc.all
    @formulari = Formulari.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf=OrderPdf.new(@formulari)
        send_data pdf.render,
        filename: "", type: "application/pdf", desposition: "inline"
      end
    end
  end

  # GET /punetoris/new
  def new
    @punetori = Punetori.new
  end

  # GET /punetoris/1/edit
  def edit
  end

  # POST /punetoris
  # POST /punetoris.json
  def create
    @punetori = Punetori.new(punetori_params)

    respond_to do |format|
      if @punetori.save
        format.html { redirect_to punetoris_path, notice: 'Punetori u krijua me sukses' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /punetoris/1
  # PATCH/PUT /punetoris/1.json
  def update
    respond_to do |format|
      if @punetori.update(punetori_params)
        format.html { redirect_to punetoris_path, notice: 'Punetori u editua me sukses.' }
        format.json { render :show, status: :ok, location: @punetori }
      else
        format.html { render :edit }
        format.json { render json: @punetori.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /punetoris/1
  # DELETE /punetoris/1.json
  def destroy
    @punetori.destroy
    respond_to do |format|
      format.html { redirect_to punetoris_url, notice: 'Punetori u fshi me sukses.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_punetori
      @punetori = Punetori.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def punetori_params
      params.require(:punetori).permit(:emri, :mbiemri, :email, :referenca, :statusi_kontrates)
    end
end

app/helpers/punetoris_helper.rb
module PunetorisHelper
  def pc(lan = "en")
    if(lan == "en")
      "PC"
    else
      if(lan == "al")
        "Kompjuter"
      end
    end
  end
  def paneli(lan = "en")
    if(lan == "en")
      "Dashboard"
    else
      if(lan == "al")
        "Paneli"
      end
    end
  end
  def appi(lan = "en")
    if(lan == "en")
      "Applications"
    else
      if(lan == "al")
        "Aplikimet"
      end
    end
  end
  def puntori(lan = "en")
    if(lan == "en")
      "Workers"
    else
      if(lan == "al")
        "Punetoret"
      end
    end
  end
  def pushimet(lan = "en")
    if(lan == "en")
      "Holidays"
    else
      if(lan == "al")
        "Pushimet"
      end
    end
  end
  def gjuha(lan = "en")
    if(lan == "en")
      "Language"
    else
      if(lan == "al")
        "Gjuha"
      end
    end
  end
  def status(lan = "en")
    if(lan == "en")
      "Statuses"
    else
      if(lan == "al")
        "Statuset"
      end
    end
  end
  def dil(lan = "en")
    if(lan == "en")
      "Logout"
    else
      if(lan == "al")
        "Shkyçu"
      end
    end
  end
  def refuzuar(lan = "en")
    if(lan == "en")
      "Rejected"
    else
      if(lan == "al")
        "Refuzuar"
      end
    end
  end
  def intervs(lan = "en")
    if(lan == "en")
      "Intervews"
    else
      if(lan == "al")
        "Intervista"
      end
    end
  end
  #_form

  def kth(lan = "en")
    if(lan == "en")
      "Back"
    else
      if(lan == "al")
        "Kthehu"
      end
    end
  end
#index
def name(lan = "en")
  if(lan == "en")
    "Name"
  else
    if(lan == "al")
      "Emri"
    end
  end
end
def surname(lan = "en")
  if(lan == "en")
    "Surname"
  else
    if(lan == "al")
      "Mbiemri"
    end
  end
end
def tel(lan = "en")
  if(lan == "en")
    "Telephone"
  else
    if(lan == "al")
      "Telefoni"
    end
  end
end
def birth_d(lan = "en")
  if(lan == "en")
    "Date of Birth"
  else
    if(lan == "al")
      "Ditelindja"
    end
  end
end
def id_n(lan = "en")
  if(lan == "en")
    "ID Number"
  else
    if(lan == "al")
      "Leternjoftimi"
    end
  end
end
def birth_p(lan = "en")
  if(lan == "en")
    "Place of Birth"
  else
    if(lan == "al")
      "Vendlindja"
    end
  end
end
def shkollimi(lan = "en")
  if(lan == "en")
    "Education"
  else
    if(lan == "al")
      "Shkollimi"
    end
  end
end
def kon_from(lan = "en")
  if(lan == "en")
    "Contract From"
  else
    if(lan == "al")
      "Kontrata Nga"
    end
  end
end
def kon_to(lan = "en")
  if(lan == "en")
    "Contract To"
  else
    if(lan == "al")
      "Kontrata |Deri"
    end
  end
end
def akstionet(lan = "en")
  if(lan == "en")
    "Actions"
  else
    if(lan == "al")
      "Aksionet"
    end
  end
end
def ndrysho(lan = "en")
  if(lan == "en")
    "EDIT"
  else
    if(lan == "al")
      "NDRYSHO"
    end
  end
end
def edit_works(lan = "en")
  if(lan == "en")
    "Editing Worker"
  else
    if(lan == "al")
      "Editimi Puntorit"
    end
  end
end
def fshije(lan = "en")
  if(lan == "en")
    "DELETE"
  else
    if(lan == "al")
      "FSHIJ"
    end
  end
end
def regj_punetorit(lan = "en")
  if(lan == "en")
    "Worker Registration"
  else
    if(lan == "al")
      "Regjistrimi Punetorit"
    end
  end
end
#show
def regj_add(lan = "en")
  if(lan == "en")
    "Add New"
  else
    if(lan == "al")
      "Shto Punetor"
    end
  end
end
def dil(lan = "en")
  if(lan == "en")
    "Log Out"
  else
    if(lan == "al")
      "Dil"
    end
  end
end
#new
def ruj(lan = "en")
  if(lan == "en")
    "Save"
  else
    if(lan == "al")
      "Ruaj"
    end
  end
end
def kerse(lan = "en")
  if(lan == "en")
    "Search"
  else
    if(lan == "al")
      "Kerko"
    end
  end
end
def ks(lan = "en")
  if(lan == "en")
    "Search by:"
  else
    if(lan == "al")
      "Kerko sipas:"
    end
  end
end

def ref(lan = "en")
  if(lan == "en")
    "References"
  else
    if(lan == "al")
      "Referenca"
    end
  end
  end
def app_h(lan = "en")
  if(lan == "en")
    "Worker History"
  else
    if(lan == "al")
      "Historia Punetorit"
    end
  end
end
end

app/views/punetoris/_condition_fields.html.erb
<div class="field borderr">
  <%= f.attribute_fields do |a| %>
    <%= ks(session[:lan]) %> <%= a.attribute_select associations: [:category, :pozis]%>
  <% end %>
  <div style="display: none;"><%= f.predicate_select %></div>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value, class: "radius_button" %>
    <%= f.submit "#{kerse(session[:lan])}", class: "radius_button" %>

  <% end %>
</div>
<style>
.radius_button, input {
     border: 0px;
    border-bottom: 1px solid rgba(134, 134, 134, 0.52);
    outline: 0;
}
.radius_button {
  margin-bottom: 40px;
  background-color: #fff;
}
select {
border: 0px;
border-bottom: 1px solid rgba(134, 134, 134, 0.52);
background-color: #fff;
padding: 2px;
outline: 0;
}
.borderr {
  margin-top: 15px;
}
</style>

app/views/punetoris/_form.html.erb
<% if current_user.admin? %>
<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">UBT</a>
            </div>
            <!-- Top Menu Items -->
          <ul class="nav navbar-right top-nav">
      <li><%= link_to("En", "/formularis/index/?lan=en") %></li>
      <li><%= link_to("Al", "/formularis/index/?lan=al") %></li>
       <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-bell"></i>
          <b class = "numri">
          <%if Formulari.where(status_id: 1).count>0%>
              <%=Formulari.where(status_id: 1).count%>
          <%end%>
          </b>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu alert-dropdown">
        <%Formulari.where(status_id: 1).each do |f|%>
          <li>
            <a href="formularis/<%=f.id%>"><%= f.emri%> <%= f.mbiemri%>
              <span class="label label-default"><%= f.pozita%></span>
            </a>
          </li>
            <%end%>
          <li class="divider"></li>
          <li>
            <%= link_to "View All", formularis_path %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to "#{dil(session[:lan])}", destroy_user_session_path, :method => 'delete', class: "fa fa-sign-out", style: "margin-right:20px;" %>
      </li>
    </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "#{paneli(session[:lan])}", dashboard_new_path, class: "fa fa-dashboard" %>
                    </li>
                    <li >
                        <%= link_to "#{appi(session[:lan])}", formularis_path, class: "fa fa-list" %>
                    </li>
                    <li   class="active">
                        <%= link_to "#{puntori(session[:lan])}", punetoris_path, class: "fa fa-users" %>
                    </li>
                    <li>
                        <%= link_to "#{pushimet(session[:lan])}" , pushimet_index_path, class: "fa fa-calendar" %>
                    </li>
                    <li>
                        <%= link_to "#{pozita(session[:lan])}", pozis_path, class: "fa fa-bars"  %>
                    </li>
                    <li>
                        <%= link_to "#{statusi(session[:lan])}", statuses_path, class: "fa fa-check-square-o" %>
                    </li>
                    <li>
                        <%= link_to "#{qytet(session[:lan])}", qytetets_path, class: "fa fa-building" %>
                    </li>
                    <li >
                        <%= link_to "#{gjuha(session[:lan])}",gjuhas_path, class: "fa fa-language" %>
                    </li>
                    <li>
                        <%= link_to "#{pc(session[:lan])}", pcs_path, class: "fa fa-laptop" %>
                    </li>
                    <li >
                        <%= link_to "#{refuzuar(session[:lan])}", refuzuars_path, class: "fa fa-adjust"  %>
                    </li>
                    <li >
                        <%= link_to "#{intervs(session[:lan])}", interviews_path, class: "fa fa-male"  %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h2 class="page-header">
                            <%= edit_works(session[:lan]) %>
                        </h2>
                         <% if notice %>
                          <p class="notice"><%= notice %></p>
                          <% elsif alert %>
                          <p class="alert"><%= alert %></p>
                          <% end %>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-users" style="color:#777;"></i>  <a style="color:#777;" href="index.html"><%= puntori(session[:lan]) %></a>
                            </li>
                            <li class="active">
                                <i class="fa fa-edit"></i><%= ndrysho(session[:lan]) %>
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->



                <div class="row">
                    <div class="col-lg-12">
                        <div class="b_g">
                            <div class="border_punetori">
                            <%= form_for(@punetori) do |f| %>
                            <div class="row">
                                <div class="field">
                                  <div class="col-sm-4">
                                    <%= f.label :emri %></div>
                                  <div class="col-sm-8">
                                    <%= f.text_field :emri, class: "punetori_input" %></div>
                                </div>
                                <div class="field">
                                  <div class="col-sm-4">
                                    <%= f.label :mbiemri %></div>
                                  <div class="col-sm-8">
                                    <%= f.text_field :mbiemri, class: "punetori_input" %></div>
                                </div>
                                <div class="field">
                                  <div class="col-sm-4">
                                    <%= f.label :email %></div>
                                  <div class="col-sm-8">
                                    <%= f.text_field :email, class: "punetori_input" %></div>
                                </div>
                                <div class="actions punetori_btn">
                                  <div class="actions formulari_btn"><%= f.submit "#{ndrysho(session[:lan])}" , style: "margin-right: 426px;" %></div>
                                </div>

                                <% end %>
                                    <%= link_to "#{kth(session[:lan])}", punetoris_path, :class => "back_btn", style: "margin-top: 35px; margin-left:15px;" %>
                            </div>
                            </div>
                        </div>
            <!-- /.container-fluid -->
                    </div>
                </div>
        <!-- /#page-wrapper -->

            </div>
  <% end %>

app/views/punetoris/edit.html.erb
<%= render 'form' %>

app/views/punetoris/index.html.erb
<% if current_user.admin? %>
<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">UBT</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
              <li><%= link_to("En", "/punetoris/index/?lan=en") %></li>
              <li><%= link_to("Al", "/punetoris/index/?lan=al") %></li>
                <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-bell"></i>
          <b class = "numri">
          <%#if Formulari.where(status_id: 1).count > 0%>

              <%#=Formulari.where(status_id: 1).count%>
          <%end%>
          </b>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu alert-dropdown">
        <%Formulari.where(status_id: 1).each do |f|%>
          <li>
            <a href="formularis/<%=f.id%>"><%= f.emri%> <%= f.mbiemri%>
              <span class="label label-default"><%= f.pozita%></span>
            </a>
          </li>
            <%end%>
          <li class="divider"></li>
          <li>
            <%= link_to "View All", formularis_path %>
          </li>
        </ul>
      </li>
                 <li>
                     <%= link_to "#{dil(session[:lan])}", destroy_user_session_path, :method => 'delete', class: "fa fa-sign-out", style: "margin-right:20px;" %>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "#{paneli(session[:lan])}", dashboard_new_path, class: "fa fa-dashboard" %>
                    </li>
                    <li >
                        <%= link_to "#{appi(session[:lan])}", formularis_path, class: "fa fa-list" %>
                    </li>
                    <li   class="active">
                        <%= link_to "#{puntori(session[:lan])}", punetoris_path, class: "fa fa-users" %>
                    </li>
                    <li>
                        <%= link_to "#{pushimet(session[:lan])}" , pushimet_index_path, class: "fa fa-calendar" %>
                    </li>
                    <li>
                        <%= link_to "#{pozita(session[:lan])}", pozis_path, class: "fa fa-bars"  %>
                    </li>
                    <li>
                        <%= link_to "#{statusi(session[:lan])}", statuses_path, class: "fa fa-check-square-o" %>
                    </li>
                    <li>
                        <%= link_to "#{qytet(session[:lan])}", qytetets_path, class: "fa fa-building" %>
                    </li>
                    <li >
                        <%= link_to "#{gjuha(session[:lan])}",gjuhas_path, class: "fa fa-language" %>
                    </li>
                    <li>
                        <%= link_to "#{pc(session[:lan])}", pcs_path, class: "fa fa-laptop" %>
                    </li>
                    <li >
                        <%= link_to "#{refuzuar(session[:lan])}", refuzuars_path, class: "fa fa-adjust"  %>
                    </li>
                    <li >
                        <%= link_to "#{intervs(session[:lan])}", interviews_path, class: "fa fa-male"  %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h2 class="page-header">
                            <%= puntori(session[:lan]) %>
                        </h2>
                         <% if notice %>
                          <p class="notice"><%= notice %></p>
                          <% elsif alert %>
                          <p class="alert"><%= alert %></p>
                          <% end %>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard" style="color:#777;"></i>  <a style="color:#777;" href="index.html"><%= paneli(session[:lan]) %></a>
                            </li>
                            <li class="active">
                                <i class="fa fa-users"></i><%= puntori(session[:lan]) %>
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->



                <div class="row">
                    <div class="col-lg-12">
                        <div class="b_g">

                            <div class="exeli">
                              <%= link_to "Excel", formularis_path(format: "xls"), class: "butoni_e pull-right fa fa-upload ", style: "color: #777;"%>
                            </div>
                            <div class="seach pull-right">
                              <%= search_form_for @search, url: search_punetoris_path, method: :post do |f| %>
                              <%= f.condition_fields do |c| %>
                              <%= render "condition_fields", f: c %>
                              <% end %>
                              <% end %>
                            </div>

                            <%= link_to "#{regj_add(session[:lan])}", new_punetori_path, class: "fa fa-plus regj_p" %>
                            <table class="table">
                                <thead>
                                  <th><%= name(session[:lan]) %></th>
                                  <th><%= surname(session[:lan]) %></th>
                                  <th>Email</th>
                                  <th><%= akstionet(session[:lan]) %></th>
                                </thead>
                                <% @punetoris.each  do |punetori| %>
                                <% if punetori.statusi_kontrates == true %>
                                <tr class = "success">
                                  <td><%= punetori.emri %></td>
                                  <td><%= punetori.mbiemri %></td>
                                  <td><%= punetori.email %></td>


                                  <% else %>
                                  <tr>
                                    <td><%= punetori.emri %></td>
                                    <td><%= punetori.mbiemri %></td>
                                    <td><%= punetori.email %></td>



                                <%end%>

                                   <% if can? :update, punetori %>
                                  <td><%= link_to "#{show(session[:lan])}", punetori_path(punetori), class: "shiko"%>
                                    <% end %>

                                        <% if can? :update, punetori %>
                                        <%= link_to "#{ndrysho(session[:lan])}", edit_punetori_path(punetori), class: "edit" %>
                                        <% end %>


                                    <%= link_to "KONTRATA", new_kontrata_path(punetori) %>


                                        <% if can? :update, punetori %>
                                        <%= link_to "#{fshije(session[:lan])}", punetori, method: :delete, data: { confirm: 'A jeni te sigurt?' }, class: "fshij" %>
                                          <% end %>
                                        </td>
                                          </tr>
                                          </tr>
                                      <% end %>

                            </table>
                            <%= link_to "#{kth(session[:lan])}", dashboard_new_path, :class => "back_btn", style: "margin-top: 35px;" %>
                        </div>
                    </div>
            <!-- /.container-fluid -->
                </div>
        </div>
        <!-- /#page-wrapper -->

    </div>

app/views/punetoris/index.xls.erb
<table class="table">
  <thead>
    <th><%= name(session[:lan]) %></th>
    <th><%= surname(session[:lan]) %></th>
    <th>Email</th>
  </thead>
  <% @punetoris.each do |punetori| %>
  <tr>
    <td><%= punetori.emri %></td>
    <td><%= punetori.mbiemri %></td>
    <td><%= punetori.email %></td>

        <% end %>
</table>